#!/bin/bash

GIT_REMOTE="https://${GITHUB_TOKEN}@github.com/olbat/ut1-blacklists"
GIT_BRANCH="master"

set -euxo pipefail

# if there are some changes in the repository: commit, tag and push them
git add -A blacklists/

if ! git diff --cached --exit-code -- blacklists/ ':!blacklists/README' > /dev/null
# (do not take in account changes that only affects the blacklists/README file
# since this file is updated every day with the date)
then
	git commit -am "Automatic blacklist update"
	tag=$(date +%Y-%m-%d)
	git tag $tag

	git remote set-url origin $GIT_REMOTE
	git push origin HEAD:$GIT_BRANCH
	git push origin tag $tag
fi
